require("dotenv").config();

import { getTradeDateYearTrades, formatDateUS, convertExcelDateToJSDate, convertExcelDateToJSDateTime, generateRandomString, generateSignedUrl } from "../common";
import { getSettlementDateYear } from "../reports/tools";
import { getSecurityInPortfolioWithoutLocationForVcon } from "./graphApiConnect";
import { uri } from "../common";
import { readEmsxEBlot, readIBEblot, uploadToGCloudBucket } from "../operations/readExcel";
import { client } from "../userManagement/auth";
import { CentralizedTrade, Vcon } from "../../models/trades";
import { formatDateNomura } from "../operations/tools";
const xlsx = require("xlsx");
const { PassThrough } = require("stream");
const { v4: uuidv4 } = require("uuid");
const axios = require("axios");
const pdf = require("pdf-parse");
const fs = require("fs");
const qpdf = require("node-qpdf");

function extractValuesVcon(lines: any) {
  let variables = [
    "Broker Code",
    "Status",
    "Buy/Sell",
    "Quantity",
    "Issue",
    "Benchmark",
    "Price",
    "Yield",
    "Principal",
    "Trade Date",
    "Acc Int",
    "Settle Date",
    "Net",
    "Spread",
    "Entry Time",
    "Customer",
    "Seq No",
    "Account",
    "User Name",
    "Audit Trail",
    "Broker Name",
    "Accrued Interest",
    "Application",
    "Benchmark Discount",
    "Benchmark Price",
    "Benchmark Yield",
    "Client Side",
    "Currency Symbol",
    "Cusip",
    "Dealer Notes",
    "Dealer Pricing Number",
    "Discount Rate",
    "End Date",
    "Factor Label",
    "Futures client broker",
    "Futures dealer broker",
    "ISIN",
    "Price (Decimal)",
    "Primary Security ID",
    "Rate",
    "Swap Sequence Number",
    "Trading System Ticket #",
    "Transaction Cost",
    "Unit Traded",
  ];
  // Prepare the variable pattern, escape special characters
  const varPattern = variables.map((v: any) => v.trim().replace(/[.*+\?^{}()|[\]\\]/g, "\\&")).join("|");

  let values: any = {};

  lines.forEach((line: any) => {
    // Split the line into segments based on the variable names
    const segments = line.split(new RegExp(`(${varPattern})`));

    for (let i = 1; i < segments.length; i += 2) {
      let varName = segments[i].trim();
      let value = "";

      if (i + 1 < segments.length) {
        // Slice the value from the segment, remove leading ':'
        value = segments[i + 1].split(":")[1]?.trim() || "";
      }

      values[varName] = value;
    }
  });

  return values;
}
function parseArray(arr: any) {
  let obj: any = {};
  for (let i = 0; i < arr.length; i++) {
    let splitString = arr[i].split(":");
    if (splitString.length === 2) {
      let key = splitString[0].trim();
      let value = splitString[1].trim();
      obj[key] = value;
    }
  }
  return obj;
}
export function renderVcon(emailContent: string): Vcon {
  const start = "Broker Code";
  const end = "** TICKET GENERATED BY BLOOMBERG **";

  // Find the start and end indices of the relevant content
  const startIndex = emailContent.indexOf(start);
  const endIndex = emailContent.indexOf(end) + end.length;

  // Extract the relevant content
  const relevantContent = emailContent.slice(startIndex, endIndex);

  let lines = relevantContent.split("\n");
  lines.pop();
  lines.pop();
  lines.pop();
  lines = lines.filter((line) => line !== "------------------------------------------------------------------------------");
  lines = lines.filter((line) => line !== "");

  let vcon: any = {};
  let main: any = lines.slice(0, 10);
  let secondary: any = lines.slice(11, -1);

  let firstParams = extractValuesVcon(main);
  let secondParams = parseArray(secondary);
  vcon = { ...firstParams, ...secondParams };

  return vcon;
}

export async function formatCentralizedRawFiles(files: any, bbbData: any, vconTrades: any, ibTrades: any, emsxTrades: any, fullFormat = false): Promise<CentralizedTrade[]> {
  let ibData = [],
    bbeData = [];
  for (let fileIndex = 0; fileIndex < files.length; fileIndex++) {
    let file = files[fileIndex];
    let url = await generateSignedUrl(file["filename"]);
    if (file["fieldname"] == "IB") {
      ibData = await readIBEblot(url);
      if (ibData.error) {
        return ibData;
      }
    } else if (file["fieldname"] == "BBE") {
      bbeData = await readEmsxEBlot(url);
      if (bbeData.error) {
        return bbeData;
      }
    }
  }
  let blot_vcons = vconTrades.map(({ "Edit Note": _, "Updated Notional": __, ...rest }: any) => rest);
  let blot_ib = ibTrades.map(({ "Edit Note": _, "Updated Notional": __, ...rest }: any) => rest);
  let blot_emsx = emsxTrades.map(({ "Edit Note": _, "Updated Notional": __, ...rest }: any) => rest);

  let blot: any = [];
  let counter = 1;
  let bbbCurrency: any = {
    $: "USD",
    A$: "AUD",
    "€": "EUR",
    "£": "GBP",
    SGD: "SGD",
  };
  let centralizedBlotterHeader: any = ["B/S", "BB Ticker", "Location", "Trade Date", "Trade Time", "Settle Date", "Price", "Notional Amount", "Settlement Amount", "Principal", "Counter Party", "Triada Trade Id", "Seq No", "ISIN", "Cuisp", "Currency", "Yield", "Accrued Interest", "Original Face", "Comm/Fee", "Trade Type", "Trade App Status"];
  // vcons already checking if duplicate trade and removes it. ib and emsx no. ib trades to be implement with their API
  for (let index = 0; index < bbbData.length; index++) {
    let obj: any = {};
    let trade = bbbData[index];
    if (trade["Status"] == "Accepted") {
      let settlementDate = getSettlementDateYear(convertExcelDateToJSDate(trade["Trade Date"]), convertExcelDateToJSDate(trade["Settle Date"]));
      obj["B/S"] = trade["Buy/Sell"];
      obj["BB Ticker"] = trade["BB Ticker"];
      obj["Location"] = trade["Location"].trim();
      obj["Trade Date"] = getTradeDateYearTrades(convertExcelDateToJSDate(trade["Trade Date"]));
      obj["Trade Time"] = trade["Entry Time"];
      obj["Settle Date"] = getTradeDateYearTrades(settlementDate);
      obj["Price"] = trade["Price (Decimal)"];
      obj["Notional Amount"] = parseFloat(trade["Notional Amount"].replace(/,/g, ""));
      obj["Settlement Amount"] = parseFloat(trade["Net"].replace(/,/g, ""));
      obj["Principal"] = parseFloat(trade["Principal"].replace(/,/g, ""));
      obj["Counter Party"] = trade["Broker Code"];
      obj["Triada Trade Id"] = trade["Triada Trade Id"];
      obj["Seq No"] = trade["Seq No"];
      obj["ISIN"] = trade["ISIN"];
      obj["Cuisp"] = trade["Cusip"];
      obj["Currency"] = bbbCurrency[trade["Currency Symbol"]];
      obj["Yield"] = trade["Yield"];
      obj["Accrued Interest"] = trade["Accrued Interest"];
      obj["Original Face"] = "1000";
      obj["Comm/Fee"] = "";
      obj["Trade Type"] = "vcons";
      obj["Trade App Status"] = trade["Trade App Status"];

      blot_vcons.push(obj);
      counter++;
    }
  }
  blot_vcons.sort((a: any, b: any) => new Date(a["Trade Date"]).getTime() - new Date(b["Trade Date"]).getTime());

  for (let index2 = 0; index2 < ibData.length; index2++) {
    let trade = ibData[index2];
    if (blot_ib.filter((ibTrade: any) => ibTrade["Triada Trade Id"] == trade["Triada Trade Id"])) {
      let obj: any = {};
      let originalFace: any = Math.abs(trade["Notional Value"] / trade["T Price"] / trade["Notional Amount"]);
      obj["B/S"] = parseFloat(trade["Notional Amount"]) > 0 ? "B" : "S";
      obj["BB Ticker"] = trade["Symbol"];
      obj["Location"] = trade["Location"].trim();
      obj["Trade Date"] = trade["Trade Date"];
      obj["Trade Time"] = trade["Trade Date Time"];
      obj["Settle Date"] = trade["Trade Date"];
      obj["Price"] = trade["T Price"];
      obj["Notional Amount"] = Math.abs(parseFloat(trade["Notional Amount"])) * originalFace;
      obj["Settlement Amount"] = Math.abs(trade["Notional Value"]);
      obj["Principal"] = Math.abs(trade["T Price"] * trade["Notional Amount"] * originalFace);
      obj["Counter Party"] = "IB";
      obj["Triada Trade Id"] = trade["Triada Trade Id"];
      obj["Seq No"] = "";
      obj["ISIN"] = "";
      obj["Cuisp"] = "";
      obj["Currency"] = "USD";
      obj["Yield"] = "";
      obj["Accrued Interest"] = "";
      obj["Original Face"] = originalFace;
      obj["Comm/Fee"] = trade["Comm/Fee"];
      obj["Trade Type"] = "ib";
      obj["Trade App Status"] = trade["Trade App Status"];

      blot_ib.push(obj);
      counter++;
    }
  }

  blot_ib.sort((a: any, b: any) => new Date(a["Trade Date"]).getTime() - new Date(b["Trade Date"]).getTime());

  for (let index3 = 0; index3 < bbeData.length; index3++) {
    let obj: any = {};
    let trade = bbeData[index3];
    if (blot_emsx.filter((emsxTrade: any) => emsxTrade["Triada Trade Id"] == trade["Triada Trade Id"])) {
      obj["B/S"] = trade["Buy/Sell"] == "Sell" ? "S" : "B";
      obj["BB Ticker"] = trade["Security"];
      obj["Location"] = trade["Location"].trim();
      obj["Trade Date"] = trade["Trade Date"];
      obj["Trade Time"] = "";
      obj["Settle Date"] = trade["Trade Date"];
      obj["Price"] = trade["Price"];
      obj["Notional Amount"] = parseFloat(trade["Notional Amount"]);
      obj["Settlement Amount"] = trade["Net"];
      obj["Principal"] = trade["Net"] * trade["Price"];
      obj["Counter Party"] = "EMSX";
      obj["Triada Trade Id"] = trade["Triada Trade Id"];
      obj["Seq No"] = "";
      obj["ISIN"] = "";
      obj["Cuisp"] = "";
      obj["Currency"] = "HKD";
      obj["Yield"] = "";
      obj["Accrued Interest"] = "";
      obj["Original Face"] = "1000";
      obj["Comm/Fee"] = "";
      obj["Trade Type"] = "emsx";
      obj["Trade App Status"] = trade["Trade App Status"];

      blot_emsx.push(obj);
      counter++;
    }
  }

  blot_emsx.sort((a: any, b: any) => new Date(a["Trade Date"]).getTime() - new Date(b["Trade Date"]).getTime());
  blot = [...blot_vcons, ...blot_ib, ...blot_emsx];
  if (blot.length > 0) {
    for (let index = 0; index < blot.length; index++) {
      let temp = blot[index];
      blot[index] = {};
      for (let i = 0; i < centralizedBlotterHeader.length; i++) {
        blot[index][centralizedBlotterHeader[i]] = temp[centralizedBlotterHeader[i]];
      }
    }

    return blot;
  } else {
    return [];
  }
}
function extractValuesFx(text: any) {
  let lines = text.split("\n");
  let output: any = {};

  lines.forEach((line: any) => {
    let colonIndex = line.indexOf(":");
    let key, value;
    if (colonIndex !== -1) {
      key = line.slice(0, colonIndex).trim();
      value = line.slice(colonIndex + 1).trim();
      output[key] = value;
    }
  });
  output = formatFxTrades(output);
  return output;
}
export function formatIbTrades(data: any, ibTrades: any, portfolio: any) {
  if (data.error) {
    return data;
  }
  let trades = [];

  try {
    for (let index = 0; index < data.length; index++) {
      let trade = data[index];

      let id;
      let object: any = {};
      if (trade["Header"] == "Data") {
        let tradeDate = convertExcelDateToJSDate(data[index]["Date/Time"]);
        let tradeDateTime = convertExcelDateToJSDateTime(data[index]["Date/Time"]);
        let trade_status = "new";
        trade["Trade Date"] = formatDateUS(tradeDate);

        trade["Settle Date"] = formatDateUS(tradeDate);
        trade["Symbol"] += " IB";

        let existingTrade = null;
        for (let ibIndex = 0; ibIndex < ibTrades.length; ibIndex++) {
          let ibTrade = ibTrades[ibIndex];
          if (trade["Symbol"] == ibTrade["BB Ticker"] && trade["Trade Date"] == ibTrade["Trade Date"] && Math.abs(ibTrade["Settlement Amount"]) == Math.abs(trade["Notional Value"])) {
            existingTrade = ibTrade;
          }
        }
        let identifier = trade["Symbol"];
        let securityInPortfolioLocation = getSecurityInPortfolioWithoutLocationForVcon(portfolio, identifier);

        if (existingTrade) {
          id = existingTrade["Triada Trade Id"];
          trade_status = "uploaded_to_app";
        } else {
          id = uuidv4();
        }
        object["Currency"] = trade["Currency"];
        object["Symbol"] = trade["Symbol"];
        // ib file has as quantity
        object["Notional Amount"] = trade["Quantity"];
        object["T Price"] = trade["T. Price"];
        object["C Price"] = data[index]["C. Price"];
        object["Notional Value"] = trade["Notional Value"];
        object["Comm/Fee"] = trade["Comm/Fee"];
        object["Basis"] = trade["Basis"];
        object["Realized P/L"] = trade["Realized P/L"];
        object["MTM P/L"] = trade["MTM P/L"];
        object["Code"] = trade["Code"];
        object["Trade Date"] = trade["Trade Date"];
        object["Trade Date Time"] = tradeDateTime;
        object["Settle Date"] = trade["Settle Date"];
        object["Triada Trade Id"] = id;
        object["Location"] = securityInPortfolioLocation && securityInPortfolioLocation != "" ? securityInPortfolioLocation : trade["Location"];
        object["Trade App Status"] = trade_status;
        trades.push(object);
      }
    }
  } catch (error) {
    return { error: error };
  }
  return trades;
}
function formatFxTrades(object: any) {
  let titles = Object.keys(object);
  let formattedObject: any = {};
  for (let index = 0; index < titles.length; index++) {
    let title = titles[index];
    if (title == "Symbol") {
      let buyCurrency = object[title].split("/")[0];
      let sellCurrency = object[title].split("/")[1];
      formattedObject["Buy Currency"] = buyCurrency;
      formattedObject["Sell Currency"] = sellCurrency;
    } else if (title == "Timestamp") {
      formattedObject["Trade Date"] = formatDateUS(object[title]);
    } else if (title == "Value Date") {
      formattedObject["Settle Date"] = formatDateUS(object[title]);
    } else if (title == "Amount 1") {
      formattedObject["Buy Amount"] = parseFloat(object[title].split(" ")[1].replace(/,/g, ""));
    } else if (title == "Amount 2") {
      formattedObject["Sell Amount"] = parseFloat(object[title].split(" ")[1].replace(/,/g, ""));
    } else {
      formattedObject[title] = object[title];
    }
  }
  return formattedObject;
}
export function renderFx(emailContent: string) {
  const start = "User";
  const end = "This e-mail";

  // Find the start and end indices of the relevant content
  const startIndex = emailContent.indexOf(start);
  const endIndex = emailContent.indexOf(end) + end.length;

  // Extract the relevant content
  const relevantContent = emailContent.slice(startIndex, endIndex);

  let fxTrade: any = {};

  let firstParams = extractValuesFx(relevantContent);

  fxTrade = { ...firstParams };

  return fxTrade;
}

export function formatEmsxTrades(data: any, emsxTrades: any, portfolio: any) {
  if (data.error) {
    return data;
  }
  let trades = [];
  try {
    for (let index = 0; index < data.length; index++) {
      let trade = data[index];
      let id;
      let object: any = {};

      let existingTrade: any = null;

      let tradeDate = !trade["Create Time (As of)"].includes("/") ? formatDateUS(new Date()) : formatDateUS(convertExcelDateToJSDate(trade["Create Time (As of)"]));
      let tradeType = trade["Side"] == "Sell" ? "S" : "B";
      for (let emsxIndex = 0; emsxIndex < emsxTrades.length; emsxIndex++) {
        let emsxTrade = emsxTrades[emsxIndex];
        // net because previous trade counted quantity as fill quantity

        if (tradeDate == emsxTrade["Trade Date"] && trade["Security"] == emsxTrade["BB Ticker"] && tradeType == emsxTrade["B/S"] && trade["FillQty"] == emsxTrade["Settlement Amount"]) {
          existingTrade = emsxTrade;
        }
      }

      trade["Trade Date"] = tradeDate;
      trade["Trade Date Time"] = tradeDate;
      let identifier = trade["Security"];
      let securityInPortfolioLocation = getSecurityInPortfolioWithoutLocationForVcon(portfolio, identifier);
      let trade_status = "new";
      if (existingTrade) {
        id = existingTrade["Triada Trade Id"];
        trade_status = "uploaded_to_app";
      } else {
        id = uuidv4();
      }
      object["Status"] = trade["Status"];
      object["Buy/Sell"] = trade["Side"];
      object["Security"] = trade["Security"];
      object["Notional Amount"] = trade["Qty"];
      object["Net"] = trade["FillQty"];
      object["Price"] = trade["LmtPr"];
      object["Trade Date"] = trade["Trade Date"];
      object["Settle Date"] = trade["Trade Date"];
      object["Triada Trade Id"] = id;
      object["Location"] = securityInPortfolioLocation;
      object["Trade App Status"] = trade_status;
      trades.push(object);
    }
  } catch (error) {
    return { error: error };
  }
  return trades;
}

export function formatNomura(tradesInput: any, start: string, end: string) {
  let startTimestamp = new Date(start).getTime() - 1 * 24 * 60 * 60 * 1000;
  let endTimestamp = new Date(end).getTime() + 1 * 24 * 60 * 60 * 1000;
  tradesInput = tradesInput.filter((trade: any, index: any) => new Date(trade["Trade Date"]).getTime() > startTimestamp && new Date(trade["Trade Date"]).getTime() < endTimestamp);
  let tradesOutput = [];
  for (let index = 0; index < tradesInput.length; index++) {
    let trade = tradesInput[index];
    let obj: any = {};
    let pset = trade["BB Ticker"].split(" ")[0] == "T" ? "default" : "EUROCLEAR";
    obj["Transaction-Type-Indicator"] = "BS";
    obj["Client-Ref"] = trade["Triada Trade Id"];
    obj["Shaped-Trade-Ref"] = trade["Triada Trade Id"];
    obj["Account-Number"] = "CPB10728";
    obj["Trade-Version"] = "NEW";
    obj["Trade-Date"] = formatDateNomura(trade["Trade Date"]);
    obj["Settlement-Date"] = formatDateNomura(trade["Settle Date"]);
    obj["BS-Indicator"] = trade["B/S"];
    obj["Security-Indicator-Type"] = "ISIN";
    obj["Security-Val"] = trade["ISIN"];
    obj["Security-Description"] = trade["BB Ticker"];
    obj["Issue-Currency"] = trade["Currency"];
    obj["Broker"] = trade["Counter Party"];
    obj["Quantity"] = trade["Notional Amount"];
    obj["Price"] = trade["Price"];
    obj["Commission-Type"] = "";
    obj["Commission-Value"] = "";
    obj["Tax"] = "";
    obj["Proceeds"] = trade["Settlement Amount"];
    obj["Proceeds-Currency"] = trade["Currency"];
    obj["Interest"] = trade["Accrued Interest"];
    obj["Prefigured-Indicator"] = "YES";
    obj["PSET"] = pset;
    obj["Repo Option"] = "";

    if (trade["Nomura Upload Status"] != "uploaded") {
      tradesOutput.push(obj);
    }
  }
  return tradesOutput;
}

export function formatConfirmation(confirmation: any, vconTrades: any) {
  let formmated = [];
  let vconNotFound = [];
  let confirmationNotFound = [];

  for (let index = 0; index < vconTrades.length; index++) {
    let vconTrade = vconTrades[index];
    let notional = parseFloat(vconTrade["Notional Amount"]);
    let settlementDate = vconTrade["Settle Date"];
    let found = false;
    for (let j = 0; j < confirmation.length; j++) {
      let confirmMessage = confirmation[j];
      confirmMessage["Notional Amount"] = confirmMessage["Notional Amount"] ? confirmMessage["Notional Amount"] : 0;
      let notionalMessage = parseFloat(confirmMessage["Notional Amount"].toString().replace(/,/g, ""));
      let settlementDateMessage = confirmMessage["Settlement Date"];
      if (((notionalMessage >= notional * 0.98 && notionalMessage <= notional * 1.02) || vconTrade["ISIN"] == confirmMessage["ISIN"]) && settlementDateMessage == settlementDate && confirmMessage["B/S"].includes(vconTrade["B/S"])) {
        let object = {
          "B/S": vconTrade["B/S"],

          "BB Ticker": vconTrade["BB Ticker"],
          ISIN: vconTrade["ISIN"],
          "Notional Amount VCON": notional,
          "Notional Amount Confirmation": notionalMessage,
          "Settlement Date": settlementDateMessage,
          "Triada Venue": confirmMessage["Triada Venue"],
          "Counter Venue": confirmMessage["Counter Venue"],
          "Broker Name": confirmMessage["Broker Name"],
          "Email Link": confirmMessage["Web Link"],

          Found: "True",
        };
        formmated.push(object);
        found = true;
        confirmation[j]["Found"] = true;
        break;
      }
    }
    if (!found) {
      let object = {
        "B/S": vconTrade["B/S"],

        "BB Ticker": vconTrade["BB Ticker"],
        ISIN: vconTrade["ISIN"],
        "Notional Amount VCON": notional,
        "Notional Amount Confirmation": "",
        "Settlement Date": settlementDate,
        "Triada Venue": "",
        "Counter Venue": "",
        "Broker Name": vconTrade["Counter Party"],
        "Email Link": "",

        Found: "Confirmation Not Found",
      };
      vconNotFound.push(object);
    }
  }

  for (let j = 0; j < confirmation.length; j++) {
    let confirmMessage = confirmation[j];
    let notionalMessage = parseFloat(confirmMessage["Notional Amount"].toString().replace(/,/g, ""));
    let settlementDateMessage = confirmMessage["Settlement Date"];
    if (!confirmMessage["Found"]) {
      let object = {
        "B/S": confirmMessage["B/S"],

        "BB Ticker": confirmMessage["BB Ticker"],
        ISIN: confirmMessage["ISIN"],

        "Notional Amount VCON": "",
        "Notional Amount Confirmation": notionalMessage,
        "Settlement Date": settlementDateMessage,
        "Triada Venue": confirmMessage["Triada Venue"],
        "Counter Venue": confirmMessage["Counter Venue"],
        "Broker Name": confirmMessage["Broker Name"],
        "Email Link": confirmMessage["Web Link"],
        Found: "Vcon Not Found",
      };
      confirmationNotFound.push(object);
    }
  }

  return [...formmated, ...vconNotFound, ...confirmationNotFound];
}
