export interface Vcon {
  "Broker Code": string;
  Status: string;
  "Buy/Sell": string;
  Quantity: string;
  Issue: string;
  Benchmark: string;
  Price: string;
  Yield: string;
  Principal: string;
  "Trade Date": string;
  "Acc Int": string;
  "Settle Date": string;
  Net: string;
  Spread: string;
  "Entry Time": string;
  Customer: string;
  "Seq No": string;
  Account: string;
  "User Name": string;
  "Audit Trail": string;
  "Broker Name": string;
  "Accrued Interest": string;
  Application: string;
  "Benchmark Discount": string;
  "Benchmark Price": string;
  "Benchmark Yield": string;
  "Client Side": string;
  "Currency Symbol": string;
  Cusip: string;
  "Dealer Notes": string;
  "Dealer Pricing Number": string;
  "Discount Rate": string;
  "End Date": string;
  "Factor Label": string;
  "Futures client broker": string;
  "Futures dealer broker": string;
  ISIN: string;
  "Price (Decimal)": string;
  "Primary Security ID": string;
  Rate: string;
  "Swap Sequence Number": string;
  "Trading System Ticket #": string;
  "Transaction Cost": string;
  "Unit Traded": string;
  "BB Ticker": string;
  "Notional Amount": string;
  Location: string | null;
  "Trade App Status": string | null;
  "Triada Trade Id": string | null;
}

export interface CentralizedTrade {
  "B/S": string;
  "BB Ticker": string;
  Location: string;
  "Trade Date": string;
  "Trade Time": string;
  "Settle Date": string;
  Price: number;
  "Notional Amount": number;
  "Settlement Amount": number;
  Principal: number;
  "Counter Party": string;
  "Triada Trade Id": string;
  "Seq No": string;
  ISIN: string;
  Cuisp: string;
  Currency: string;
  Yield: string;
  "Accrued Interest": number;
  "Original Face": number;
  "Comm/Fee": number;
  "Trade Type": string;
  "Trade App Status": string;
  "Updated Notional": number | null;
  timestamp: number;
  "Nomura Upload Status": string | null;
  "Last Nomura Generated": string | null;
  "Broker Full Name & Account": string | null;
  "Broker Email": string | null;
  "Settlement Venue": string | null;
  "Primary (True/False)": string | null;
  "Broker Email Status": string | null;
  "App Check Test": string | null;
  "Portfolio ID": string;
  Resolved: boolean;
  Id: string;
  "Front Office Note": string;
  "Front Office Check": boolean;
}
export interface CentralizedTradeMTDRlzd extends CentralizedTrade {
  "Rlzd P&L Amount": number | undefined;
  "Price Diff": number | undefined;
  Rlzd: string | undefined;
  "Average Cost MTD": number;
}
export interface CentralizedTradeInDB {
  b_s: string;
  bb_ticker: string;
  location: string;
  trade_date: string;
  trade_time: string;
  settle_date: string;
  price: number;
  notional_amount: number;
  settlement_amount: number;
  principal: number;
  counter_party: string;
  triada_trade_id: string;
  seq_no: string;
  isin: string;
  cuisp: string;
  currency: string;
  yield: string;
  accrued_interest: number;
  original_face: number;
  comm_fee: number;
  trade_type: string;
  updated_notional: number | null;
  timestamp: number;
  nomura_upload_status: string | null;
  last_nomura_generated: string | null;
  broker_full_name_account: string | null;
  broker_email: string | null;
  settlement_venue: string | null;
  primary_market: boolean;
  broker_email_status: string | null;
  id: string;
  portfolio_id: string;
  front_office_check: boolean;
  resolved: boolean;
  front_office_note: string;
}

export interface NewIssue {
  "BB Ticker": string;
  "Issue Price": string;
  "Settle Date": string;
  ISIN: string;
  Currency: string;
  emailId: string;
  "Reoffer Price": string | null;
  "Treasury & Spread": string;
  "App Check Test": string;
}
