export interface Vcon {
  "Broker Code": string;
  Status: string;
  "Buy/Sell": string;
  Quantity: string;
  Issue: string;
  Benchmark: string;
  Price: string;
  Yield: string;
  Principal: string;
  "Trade Date": string;
  "Acc Int": string;
  "Settle Date": string;
  Net: string;
  Spread: string;
  "Entry Time": string;
  Customer: string;
  "Seq No": string;
  Account: string;
  "User Name": string;
  "Audit Trail": string;
  "Broker Name": string;
  "Accrued Interest": string;
  Application: string;
  "Benchmark Discount": string;
  "Benchmark Price": string;
  "Benchmark Yield": string;
  "Client Side": string;
  "Currency Symbol": string;
  Cusip: string;
  "Dealer Notes": string;
  "Dealer Pricing Number": string;
  "Discount Rate": string;
  "End Date": string;
  "Factor Label": string;
  "Futures client broker": string;
  "Futures dealer broker": string;
  ISIN: string;
  "Price (Decimal)": string;
  "Primary Security ID": string;
  Rate: string;
  "Swap Sequence Number": string;
  "Trading System Ticket #": string;
  "Transaction Cost": string;
  "Unit Traded": string;
  "BB Ticker": string;
  "Notional Amount": string;
  Location: string | null;
  "Trade App Status": string | null;
  "Triada Trade Id": string | null;
}

export interface CentralizedTrade {
  "B/S": string;
  "BB Ticker": string;
  Location: string;
  "Trade Date": string;
  "Trade Time": string;
  "Settle Date": string;
  Price: string;
  "Notional Amount": string;
  "Settlement Amount": string;
  Principal: string;
  "Counter Party": string;
  "Triada Trade Id": string;
  "Seq No": string;
  ISIN: string;
  Cuisp: string;
  Currency: string;
  Yield: string;
  "Accrued Interest": string;
  "Original Face": string;
  "Comm/Fee": string;
  "Trade Type": string;
  "Trade App Status": string;
  "Updated Notional": string;
  Timestamp: number;
  "Nomura Upload Status": string;
  "Last Nomura Generated": string;
  "Broker Full Name & Account": string;
  "Broker Email": string;
  "Settlement Venue": string;
  "Primary (True/False)": string;
  "Broker Email Status": string;
  "App Check Test": string;
}
export interface NewIssue {
  "BB Ticker": string;
  "Issue Price": string;
  "Settle Date": string;
  ISIN: string;
  Currency: string;
  emailId: string;
  "Reoffer Price": string | null;
  "Treasury & Spread": string;
  "App Check Test": string;
}
