export class vconWithBBTicker {
    constructor(
    public  brokerCode: {"Broker Code": string},
    public Status: string,
    public buySell: {'Buy/Sell':string},
    public Quantity: string,
    public Issue: string,
    public Benchmark: string,
    public Price: string,
    public Yield: string,
    public Principal: string,
    public tradeDate: {"Trade Date":string},
    public accInt: {'Acc Int': string},
    public settleDate: {'Settle Date': string},
    public Net: string,
    public Spread: string,
    public entryTime: {'Entry Time': string},
    public Customer: string,
    public seqNo: {'Seq No': string},
    public Account: string,
    public brokerName : {'Broker Name': string},
    public accruedInterest : {'Accrued Interest': string},
    public Application: string,
    // public 'Benchmark Discount': string,
    // public 'Benchmark Price': string,
    // public 'Benchmark Yield': string,
    // public 'Client Side': string,
    // public 'Currency Symbol': string,
    // public Cusip: string,
    // public 'Dealer Notes': string,
    // public 'Dealer Pricing Number': string,
    // public 'Discount Rate': string,
    // public 'End Date': string,
    // public 'Factor Label': string,
    // public 'Futures client broker': string,
    // public 'Futures dealer broker': string,
    // public ISIN: string,
    // public 'Price (Decimal)': string,
    // public 'Primary Security ID': string,
    // public Rate: string,
    // public 'Swap Sequence Number': string,
    // public 'Trading System Ticket #': string,
    // public 'Transaction Cost': string,
    // public 'Accrued Number of Days': string,
    // public 'Benchmark Quantity': string,
    // public 'BYSL/EBND Voice UUID': string,
    // public 'Cover Value': string,
    // public 'Cross Currency Currency': string,
    // public 'Cross Currency FX Rate': string,
    // public 'Cross Currency Net': string,
    // public 'Exec ID': string,
    // public 'Firm Price': string,
    // public 'Price Type': string,
    // public 'Trade Status Number': string,
    // public 'Unit Traded': string,
    // public 'BB Ticker': string,
      
      ) { }
  }
  